services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - krmu_bot_pgdata:/var/lib/postgresql/data

volumes:
  krmu_bot_pgdata:
