"""added user

Revision ID: fe75658f2214
Revises: 690dd55a1195
Create Date: 2024-04-30 22:30:38.941356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe75658f2214'
down_revision: Union[str, None] = '690dd55a1195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_questioned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'user_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'user_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_questioned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
